import Head from "next/head";
import styles from "./Home.module.css";
import Header from "../components/Header";
import HeroBlock from "../components/HeroBlock";
import Ideas from "../components/Ideas/Ideas";

export default function Home() {
  return (
    <div>
      <Head>
        <title>now?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.content}>
        <Ideas />
        <HeroBlock />
      </div>
    </div>
  );
}
